apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-system.fullname" . }}
  labels:
    {{- include "agent-system.labels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agent-system.selectorLabels" . }}
